/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface CartItem {
  'customNotes' : [] | [string],
  'productId' : bigint,
  'quantity' : bigint,
}
export type ExternalBlob = Uint8Array;
export type OrderStatus = { 'new' : null } |
  { 'rejected' : null } |
  { 'contacted' : null } |
  { 'confirmed' : null };
export type Principal = Principal;
export interface Product {
  'id' : bigint,
  'specifications' : Array<[string, string]>,
  'imageBlob' : [] | [ExternalBlob],
  'stockStatus' : StockStatus,
  'name' : string,
  'description' : string,
  'category' : ProductCategory,
  'image' : string,
  'price' : [] | [bigint],
}
export type ProductCategory = { 'wd40Products' : null } |
  { 'compressedAsbestosJointingSheets' : null } |
  { 'nonAsbestosJointingSheets' : null } |
  { 'mechanicalPackings' : null } |
  { 'fluidSealants' : null };
export type StockStatus = { 'inStock' : bigint } |
  { 'outOfStock' : null } |
  { 'limited' : bigint };
export type Time = bigint;
export interface UserProfile {
  'name' : string,
  'company' : [] | [string],
  'phone' : [] | [string],
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface WhatsAppOrder {
  'id' : bigint,
  'status' : OrderStatus,
  'customerPrincipal' : Principal,
  'cartItems' : Array<CartItem>,
  'whatsappNumber' : string,
  'timestamp' : Time,
}
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addProduct' : ActorMethod<[Product], bigint>,
  'addProducts' : ActorMethod<[Array<Product>], Array<bigint>>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'checkStock' : ActorMethod<[bigint], StockStatus>,
  'deleteProduct' : ActorMethod<[bigint], undefined>,
  'deleteProductImage' : ActorMethod<[bigint], undefined>,
  'filterProductsByStock' : ActorMethod<[StockStatus], Array<Product>>,
  'getAllOrders' : ActorMethod<[], Array<WhatsAppOrder>>,
  'getAllProducts' : ActorMethod<[], Array<Product>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getCompanyContactGmail' : ActorMethod<[], string>,
  'getCustomDomainRequest' : ActorMethod<[], [] | [string]>,
  'getMyOrders' : ActorMethod<[], Array<WhatsAppOrder>>,
  'getOrder' : ActorMethod<[bigint], [] | [WhatsAppOrder]>,
  'getProductsByCategory' : ActorMethod<[ProductCategory], Array<Product>>,
  'getProductsBySearch' : ActorMethod<[string], Array<Product>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'setCustomDomainRequest' : ActorMethod<[string], undefined>,
  'submitWhatsAppOrder' : ActorMethod<[Array<CartItem>, string], bigint>,
  'updateCompanyContactGmail' : ActorMethod<[string], undefined>,
  'updateOrderStatus' : ActorMethod<[bigint, OrderStatus], undefined>,
  'updateProduct' : ActorMethod<[bigint, Product], undefined>,
  'uploadProductImage' : ActorMethod<[bigint, ExternalBlob], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];