/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const ExternalBlob = IDL.Vec(IDL.Nat8);
export const StockStatus = IDL.Variant({
  'inStock' : IDL.Nat,
  'outOfStock' : IDL.Null,
  'limited' : IDL.Nat,
});
export const ProductCategory = IDL.Variant({
  'wd40Products' : IDL.Null,
  'compressedAsbestosJointingSheets' : IDL.Null,
  'nonAsbestosJointingSheets' : IDL.Null,
  'mechanicalPackings' : IDL.Null,
  'fluidSealants' : IDL.Null,
});
export const Product = IDL.Record({
  'id' : IDL.Nat,
  'specifications' : IDL.Vec(IDL.Tuple(IDL.Text, IDL.Text)),
  'imageBlob' : IDL.Opt(ExternalBlob),
  'stockStatus' : StockStatus,
  'name' : IDL.Text,
  'description' : IDL.Text,
  'category' : ProductCategory,
  'image' : IDL.Text,
  'price' : IDL.Opt(IDL.Nat),
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const OrderStatus = IDL.Variant({
  'new' : IDL.Null,
  'rejected' : IDL.Null,
  'contacted' : IDL.Null,
  'confirmed' : IDL.Null,
});
export const Principal = IDL.Principal;
export const CartItem = IDL.Record({
  'customNotes' : IDL.Opt(IDL.Text),
  'productId' : IDL.Nat,
  'quantity' : IDL.Nat,
});
export const Time = IDL.Int;
export const WhatsAppOrder = IDL.Record({
  'id' : IDL.Nat,
  'status' : OrderStatus,
  'customerPrincipal' : Principal,
  'cartItems' : IDL.Vec(CartItem),
  'whatsappNumber' : IDL.Text,
  'timestamp' : Time,
});
export const UserProfile = IDL.Record({
  'name' : IDL.Text,
  'company' : IDL.Opt(IDL.Text),
  'phone' : IDL.Opt(IDL.Text),
});

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addProduct' : IDL.Func([Product], [IDL.Nat], []),
  'addToCart' : IDL.Func([IDL.Nat, IDL.Nat, IDL.Opt(IDL.Text)], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'checkStock' : IDL.Func([IDL.Nat], [StockStatus], ['query']),
  'deleteProduct' : IDL.Func([IDL.Nat], [], []),
  'deleteProductImage' : IDL.Func([IDL.Nat], [], []),
  'filterProductsByStock' : IDL.Func(
      [StockStatus],
      [IDL.Vec(Product)],
      ['query'],
    ),
  'getAllOrders' : IDL.Func([], [IDL.Vec(WhatsAppOrder)], ['query']),
  'getAllProducts' : IDL.Func([], [IDL.Vec(Product)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getCart' : IDL.Func([], [IDL.Vec(CartItem)], ['query']),
  'getCompanyContactGmail' : IDL.Func([], [IDL.Text], ['query']),
  'getCustomDomainRequest' : IDL.Func([], [IDL.Opt(IDL.Text)], ['query']),
  'getMyOrders' : IDL.Func([], [IDL.Vec(WhatsAppOrder)], ['query']),
  'getOrder' : IDL.Func([IDL.Nat], [IDL.Opt(WhatsAppOrder)], ['query']),
  'getProductsByCategory' : IDL.Func(
      [ProductCategory],
      [IDL.Vec(Product)],
      ['query'],
    ),
  'getProductsBySearch' : IDL.Func([IDL.Text], [IDL.Vec(Product)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'removeFromCart' : IDL.Func([IDL.Nat], [], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'setCustomDomainRequest' : IDL.Func([IDL.Text], [], []),
  'submitWhatsAppOrder' : IDL.Func(
      [IDL.Vec(CartItem), IDL.Text],
      [IDL.Nat],
      [],
    ),
  'updateCompanyContactGmail' : IDL.Func([IDL.Text], [], []),
  'updateOrderStatus' : IDL.Func([IDL.Nat, OrderStatus], [], []),
  'updateProduct' : IDL.Func([IDL.Nat, Product], [], []),
  'uploadProductImage' : IDL.Func([IDL.Nat, ExternalBlob], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const ExternalBlob = IDL.Vec(IDL.Nat8);
  const StockStatus = IDL.Variant({
    'inStock' : IDL.Nat,
    'outOfStock' : IDL.Null,
    'limited' : IDL.Nat,
  });
  const ProductCategory = IDL.Variant({
    'wd40Products' : IDL.Null,
    'compressedAsbestosJointingSheets' : IDL.Null,
    'nonAsbestosJointingSheets' : IDL.Null,
    'mechanicalPackings' : IDL.Null,
    'fluidSealants' : IDL.Null,
  });
  const Product = IDL.Record({
    'id' : IDL.Nat,
    'specifications' : IDL.Vec(IDL.Tuple(IDL.Text, IDL.Text)),
    'imageBlob' : IDL.Opt(ExternalBlob),
    'stockStatus' : StockStatus,
    'name' : IDL.Text,
    'description' : IDL.Text,
    'category' : ProductCategory,
    'image' : IDL.Text,
    'price' : IDL.Opt(IDL.Nat),
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const OrderStatus = IDL.Variant({
    'new' : IDL.Null,
    'rejected' : IDL.Null,
    'contacted' : IDL.Null,
    'confirmed' : IDL.Null,
  });
  const Principal = IDL.Principal;
  const CartItem = IDL.Record({
    'customNotes' : IDL.Opt(IDL.Text),
    'productId' : IDL.Nat,
    'quantity' : IDL.Nat,
  });
  const Time = IDL.Int;
  const WhatsAppOrder = IDL.Record({
    'id' : IDL.Nat,
    'status' : OrderStatus,
    'customerPrincipal' : Principal,
    'cartItems' : IDL.Vec(CartItem),
    'whatsappNumber' : IDL.Text,
    'timestamp' : Time,
  });
  const UserProfile = IDL.Record({
    'name' : IDL.Text,
    'company' : IDL.Opt(IDL.Text),
    'phone' : IDL.Opt(IDL.Text),
  });
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addProduct' : IDL.Func([Product], [IDL.Nat], []),
    'addToCart' : IDL.Func([IDL.Nat, IDL.Nat, IDL.Opt(IDL.Text)], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'checkStock' : IDL.Func([IDL.Nat], [StockStatus], ['query']),
    'deleteProduct' : IDL.Func([IDL.Nat], [], []),
    'deleteProductImage' : IDL.Func([IDL.Nat], [], []),
    'filterProductsByStock' : IDL.Func(
        [StockStatus],
        [IDL.Vec(Product)],
        ['query'],
      ),
    'getAllOrders' : IDL.Func([], [IDL.Vec(WhatsAppOrder)], ['query']),
    'getAllProducts' : IDL.Func([], [IDL.Vec(Product)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getCart' : IDL.Func([], [IDL.Vec(CartItem)], ['query']),
    'getCompanyContactGmail' : IDL.Func([], [IDL.Text], ['query']),
    'getCustomDomainRequest' : IDL.Func([], [IDL.Opt(IDL.Text)], ['query']),
    'getMyOrders' : IDL.Func([], [IDL.Vec(WhatsAppOrder)], ['query']),
    'getOrder' : IDL.Func([IDL.Nat], [IDL.Opt(WhatsAppOrder)], ['query']),
    'getProductsByCategory' : IDL.Func(
        [ProductCategory],
        [IDL.Vec(Product)],
        ['query'],
      ),
    'getProductsBySearch' : IDL.Func([IDL.Text], [IDL.Vec(Product)], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'removeFromCart' : IDL.Func([IDL.Nat], [], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'setCustomDomainRequest' : IDL.Func([IDL.Text], [], []),
    'submitWhatsAppOrder' : IDL.Func(
        [IDL.Vec(CartItem), IDL.Text],
        [IDL.Nat],
        [],
      ),
    'updateCompanyContactGmail' : IDL.Func([IDL.Text], [], []),
    'updateOrderStatus' : IDL.Func([IDL.Nat, OrderStatus], [], []),
    'updateProduct' : IDL.Func([IDL.Nat, Product], [], []),
    'uploadProductImage' : IDL.Func([IDL.Nat, ExternalBlob], [], []),
  });
};

export const init = ({ IDL }) => { return []; };